-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT TREE.ITEM_ID
    FROM ITEM_TREE AS TREE
       , ITEM_INFO AS INFO
    WHERE 1=1
    AND PARENT_ITEM_ID IS NOT NULL
    AND TREE.PARENT_ITEM_ID = INFO.ITEM_ID
    AND INFO.RARITY = 'RARE'
    )
ORDER BY ITEM_ID DESC
;